version: '3'
services:
    nginx:
        restart: always
        build:
            context: ./Nginx
        container_name: "nginx"
        volumes:
        - ./Nginx/logs:/var/log/nginx
        ports:
        - '8088:80'
    redis:
        image: redis:5
        container_name: "redis"
        ports:                
            - "6379:6379"  

    mongodb:          
        image: mongo    
        restart: always 
        container_name: "mongodb"
        ports:                
            - "27018:27017"  

    polling_server:
        build: 
            context: ./PollingServer
        ports:
            - "3000:3000"
        container_name: "polling_server"
        volumes:
            - ./PollingServer:/usr/app
        depends_on: 
            - mongodb
            - redis

    python_server:
        build: 
            context: ./Server
        ports:
            - "5000:3000"
        container_name: "python_server"
        volumes:
            - ./Server:/usr/app
        depends_on: 
            - mongodb
            - redis
    


    vue_front:
        build: vuefront
        ports:
            - "8080:8080"
        container_name: "vue_front"
        volumes:
            - ./vuefront:/usr/app


    